-- Esquema para MySQL (Hostinger). Importalo desde hPanel > Bases de datos
-- > phpMyAdmin, en la base que hayas creado, ANTES de cambiar config.php
-- a driver 'mysql'.

CREATE TABLE IF NOT EXISTS usuarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  rol ENUM('admin','arquitecto','cliente','director') NOT NULL,
  foto VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS obras (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(190) NOT NULL,
  ubicacion VARCHAR(190),
  cliente_id INT UNSIGNED NULL,
  arquitecto_id INT UNSIGNED NULL,
  director_id INT UNSIGNED NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'en_curso',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  FOREIGN KEY (arquitecto_id) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS etapas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  orden INT NOT NULL DEFAULT 0,
  fecha DATE NULL,
  descripcion TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fotos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  etapa_id INT UNSIGNED NULL,
  archivo VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255) NULL,
  subido_por INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (etapa_id) REFERENCES etapas(id) ON DELETE SET NULL,
  FOREIGN KEY (subido_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS presupuestos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  concepto VARCHAR(190) NOT NULL,
  monto DECIMAL(14,2) NOT NULL,
  moneda CHAR(3) NOT NULL DEFAULT 'ARS',
  fecha DATE NOT NULL,
  detalle TEXT NULL,
  monto_oculto TINYINT(1) NOT NULL DEFAULT 0,
  cargado_por INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (cargado_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS eventos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  titulo VARCHAR(190) NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NULL,
  detalle TEXT NULL,
  cargado_por INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (cargado_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS novedades (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  texto TEXT NULL,
  archivo VARCHAR(255) NULL,
  autor_id INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS documentos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  categoria VARCHAR(20) NOT NULL,
  titulo VARCHAR(190) NOT NULL,
  archivo VARCHAR(255) NOT NULL,
  nombre_original VARCHAR(255) NOT NULL,
  tamano INT UNSIGNED NOT NULL DEFAULT 0,
  subido_por INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (subido_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mensajes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  autor_id INT UNSIGNED NULL,
  texto TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS asistente_mensajes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT UNSIGNED NOT NULL,
  obra_id INT UNSIGNED NOT NULL,
  rol VARCHAR(10) NOT NULL,
  texto TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS obra_info (
  obra_id INT UNSIGNED NOT NULL,
  campo VARCHAR(40) NOT NULL,
  valor TEXT NOT NULL,
  PRIMARY KEY (obra_id, campo),
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS propietarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  nombre VARCHAR(190) NOT NULL,
  apellido VARCHAR(190) NOT NULL,
  dni VARCHAR(8) NOT NULL,
  cuit VARCHAR(11) NULL,
  fecha_nacimiento DATE NULL,
  nacionalidad VARCHAR(190) NULL,
  estado_civil VARCHAR(40) NULL,
  domicilio VARCHAR(190) NULL,
  telefono VARCHAR(60) NULL,
  email VARCHAR(190) NULL,
  actualizado_por INT UNSIGNED NULL,
  updated_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (actualizado_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pagos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  fecha DATE NOT NULL,
  concepto VARCHAR(190) NOT NULL,
  monto DECIMAL(14,2) NOT NULL,
  moneda CHAR(3) NOT NULL DEFAULT 'ARS',
  detalle TEXT NULL,
  comprobante VARCHAR(255) NULL,
  comprobante_nombre VARCHAR(255) NULL,
  comprobante_subido_por INT UNSIGNED NULL,
  cargado_por INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (comprobante_subido_por) REFERENCES usuarios(id) ON DELETE SET NULL,
  FOREIGN KEY (cargado_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contactos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  obra_id INT UNSIGNED NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  nombre VARCHAR(190) NOT NULL,
  empresa VARCHAR(190) NULL,
  rubro VARCHAR(190) NULL,
  telefono VARCHAR(60) NULL,
  email VARCHAR(190) NULL,
  notas TEXT NULL,
  cargado_por INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (cargado_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contacto_archivos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  contacto_id INT UNSIGNED NOT NULL,
  obra_id INT UNSIGNED NOT NULL,
  titulo VARCHAR(190) NOT NULL,
  archivo VARCHAR(255) NOT NULL,
  nombre_original VARCHAR(255) NOT NULL,
  tamano INT UNSIGNED NOT NULL DEFAULT 0,
  subido_por INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (contacto_id) REFERENCES contactos(id) ON DELETE CASCADE,
  FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE,
  FOREIGN KEY (subido_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
